---
- name: Install GNU Screen
  ansible.builtin.package:
    name: screen
    state: present
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Copy .screenrc
  ansible.builtin.copy:
    src: files/.screenrc
    dest: "{{ ansible_facts['env'].HOME }}/.screenrc"
