---
- name: Install GNU Screen
  ansible.builtin.package:
    name: screen
    state: present
  become: true

- name: Copy .screenrc
  ansible.builtin.copy:
    src: files/.screenrc
    dest: "{{ ansible_facts['env'].HOME }}/.screenrc"
