---
- name: Install vim
  ansible.builtin.package:
    name: vim
    state: present
  become: "{{ ansible_facts['os_family'] != 'Darwin' }}"

- name: Copy vimrc
  ansible.builtin.copy:
    src: files/.vimrc
    dest: "{{ ansible_facts['env'].HOME }}/.vimrc"
